package com.example;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class TestPrimeCheck {
    @Test public void testSomeLibraryMethod() {
        PrimeCheck classUnderTest = new PrimeCheck();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.isPrimeOrNot(8));
    }
}
